// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cryptoAnalysisScraper.core.database;

namespace cryptoAnalysisScraper.Migrations
{
    [DbContext(typeof(MariaContext))]
    [Migration("20190901221257_CreateUserTable")]
    partial class CreateUserTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("cryptoAnalysisScraper.core.crawler.models.UserPageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Activity");

                    b.Property<string>("Age");

                    b.Property<string>("DateRegistered");

                    b.Property<string>("Gender");

                    b.Property<string>("LastActive");

                    b.Property<string>("LocalTime");

                    b.Property<string>("Location");

                    b.Property<string>("Merit");

                    b.Property<string>("Name");

                    b.Property<string>("Position");

                    b.Property<string>("Posts");

                    b.Property<DateTime>("RetreivedAt");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
